//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Magaza77.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string Kategori { get; set; }
        public int Fiyati { get; set; }
        public int Adet { get; set; }
        public string Aciklama { get; set; }
    }
}
