//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Magaza77.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkililer
    {
        public int YetkiliID { get; set; }
        public string YetkiliAdi { get; set; }
        public string Sifre { get; set; }
    }
}
